//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MSBuildLogsExtended.EntityFrameworkContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;

    public partial class MSBuildLogsExtendedEntities : DbContext
    {
        public MSBuildLogsExtendedEntities()
            : base("name=MSBuildLogsExtendedEntities")
        {
        }
    

        public DbSet<Build> Builds { get; set; }



        public DbSet<BuildEventCode> BuildEventCodes { get; set; }



        public DbSet<BuildLog> BuildLogs { get; set; }



        public DbSet<Solution> Solutions { get; set; }




        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

			#region #1.1 MSBuildLogsExtended.Build

			// A. Foreign Keys, tables referenced to this table
			// A.1. BuildLogs - Build
            modelBuilder.Entity<Build>()
                .HasMany(e => e.BuildLogs)
                .WithRequired(e => e.Build)
				.HasForeignKey(e => e.BuildId)
                .WillCascadeOnDelete(false);


			// B. Special Type Property

			#endregion #1.1 MSBuildLogsExtended.Build


			#region #1.2 MSBuildLogsExtended.BuildEventCode

			// A. Foreign Keys, tables referenced to this table
			// A.1. BuildLogs - BuildEventCode
            modelBuilder.Entity<BuildEventCode>()
                .HasMany(e => e.BuildLogs)
                .WithRequired(e => e.BuildEventCode)
				.HasForeignKey(e => e.BuildEventCodeId)
                .WillCascadeOnDelete(false);


			// B. Special Type Property

			#endregion #1.2 MSBuildLogsExtended.BuildEventCode


			#region #1.3 MSBuildLogsExtended.BuildLog

			// A. Foreign Keys, tables referenced to this table

			// B. Special Type Property

			#endregion #1.3 MSBuildLogsExtended.BuildLog


			#region #1.4 MSBuildLogsExtended.Solution

			// A. Foreign Keys, tables referenced to this table
			// A.1. Builds - Solution
            modelBuilder.Entity<Solution>()
                .HasMany(e => e.Builds)
                .WithRequired(e => e.Solution)
				.HasForeignKey(e => e.SolutionId)
                .WillCascadeOnDelete(false);


			// B. Special Type Property

			#endregion #1.4 MSBuildLogsExtended.Solution


        }


    }
}

