//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.EntityFrameworkContext
{
    using System;
    using System.Collections.Generic;
    using Microsoft.EntityFrameworkCore;

    #region partial class Build

    public partial class Build 
    {
        public Build ()
        {
            this.BuildLog = new HashSet<BuildLog>();

        }

        public System.Int64 Id { get; set; }
        public System.Int32 SolutionId { get; set; }
        public System.String Name { get; set; }
        public System.String Description { get; set; }
        public System.DateTime BuildStartTime { get; set; }


        public Solution Solution { get; set; }
        public ICollection<BuildLog> BuildLog { get; set; }


    }
	
	#endregion partial class Build



	#region partial class BuildEventCode

    public partial class BuildEventCode 
    {
        public BuildEventCode ()
        {
            this.BuildLog = new HashSet<BuildLog>();

        }

        public System.Int32 Id { get; set; }
        public System.String EventCode { get; set; }
        public System.String Description { get; set; }


        public ICollection<BuildLog> BuildLog { get; set; }


    }
	
	#endregion partial class BuildEventCode



	#region partial class BuildLog

    public partial class BuildLog 
    {
        public BuildLog ()
        {

        }

        public System.Int64 Id { get; set; }
        public System.Int64 BuildId { get; set; }
        public System.Int32 BuildEventCodeId { get; set; }
        public System.String Message { get; set; }
        public System.DateTime EventTime { get; set; }


        public Build Build { get; set; }
        public BuildEventCode BuildEventCode { get; set; }


    }
	
	#endregion partial class BuildLog



	#region partial class Solution

    public partial class Solution 
    {
        public Solution ()
        {
            this.Build = new HashSet<Build>();

        }

        public System.Int32 Id { get; set; }
        public System.String ExternalParentId { get; set; }
        public System.String Name { get; set; }
        public System.String Description { get; set; }


        public ICollection<Build> Build { get; set; }


    }
	
	#endregion partial class Solution





}