//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
	using Windows.ApplicationModel.Resources;    
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    public class UIStringResourcePerEntityBuildEventCode {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("MSBuildLogsExtended.Resources.WinRT/UIStringResourcePerEntityBuildEventCode");
        
        public UIStringResourcePerEntityBuildEventCode() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "BuildEventCode"".
        /// </summary>
        public static string BuildEventCode {
            get {
                return resourceLoader.GetString("BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Loading BuildEventCode ..."".
        /// </summary>
        public static string Loading_BuildEventCode____ {
            get {
                return resourceLoader.GetString("Loading_BuildEventCode____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please select BuildEventCode ..."".
        /// </summary>
        public static string Please_select_BuildEventCode____ {
            get {
                return resourceLoader.GetString("Please_select_BuildEventCode____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rss Title of BuildEventCode"".
        /// </summary>
        public static string Rss_Title_of_BuildEventCode {
            get {
                return resourceLoader.GetString("Rss_Title_of_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rss Description of BuildEventCode"".
        /// </summary>
        public static string Rss_Description_of_BuildEventCode {
            get {
                return resourceLoader.GetString("Rss_Description_of_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "AddNew BuildEventCode"".
        /// </summary>
        public static string AddNew_BuildEventCode {
            get {
                return resourceLoader.GetString("AddNew_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Delete BuildEventCode"".
        /// </summary>
        public static string Delete_BuildEventCode {
            get {
                return resourceLoader.GetString("Delete_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Details BuildEventCode"".
        /// </summary>
        public static string Details_BuildEventCode {
            get {
                return resourceLoader.GetString("Details_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Edit BuildEventCode"".
        /// </summary>
        public static string Edit_BuildEventCode {
            get {
                return resourceLoader.GetString("Edit_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdDescription {
            get {
                return resourceLoader.GetString("IdDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string Id {
            get {
                return resourceLoader.GetString("Id");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return resourceLoader.GetString("IdRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdToolTip {
            get {
                return resourceLoader.GetString("IdToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id has validation error"".
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("IdValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Id validation regular expression"".
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return resourceLoader.GetString("IdValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string Id_is_required {
            get {
                return resourceLoader.GetString("Id_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Event Code"".
        /// </summary>
        public static string EventCodeDescription {
            get {
                return resourceLoader.GetString("EventCodeDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Event Code"".
        /// </summary>
        public static string EventCode {
            get {
                return resourceLoader.GetString("EventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Event Code is required"".
        /// </summary>
        public static string EventCodeRequiredErrorMessage {
            get {
                return resourceLoader.GetString("EventCodeRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Event Code"".
        /// </summary>
        public static string EventCodeToolTip {
            get {
                return resourceLoader.GetString("EventCodeToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Event Code has validation error"".
        /// </summary>
        public static string EventCodeValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("EventCodeValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Event Code validation regular expression"".
        /// </summary>
        public static string EventCodeValueValidationExpression {
            get {
                return resourceLoader.GetString("EventCodeValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EventCode is required"".
        /// </summary>
        public static string EventCode_is_required {
            get {
                return resourceLoader.GetString("EventCode_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The length of EventCode should be 0 to 100"".
        /// </summary>
        public static string The_length_of_EventCode_should_be_0_to_100 {
            get {
                return resourceLoader.GetString("The_length_of_EventCode_should_be_0_to_100");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionDescription {
            get {
                return resourceLoader.GetString("DescriptionDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string Description {
            get {
                return resourceLoader.GetString("Description");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description is required"".
        /// </summary>
        public static string DescriptionRequiredErrorMessage {
            get {
                return resourceLoader.GetString("DescriptionRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return resourceLoader.GetString("DescriptionToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description has validation error"".
        /// </summary>
        public static string DescriptionValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("DescriptionValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Description validation regular expression"".
        /// </summary>
        public static string DescriptionValueValidationExpression {
            get {
                return resourceLoader.GetString("DescriptionValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The length of Description should be 0 to 1500"".
        /// </summary>
        public static string The_length_of_Description_should_be_0_to_1500 {
            get {
                return resourceLoader.GetString("The_length_of_Description_should_be_0_to_1500");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return resourceLoader.GetString("Value");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Value of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Value of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return resourceLoader.GetString("Name");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Name of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Name of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Identifier In String"".
        /// </summary>
        public static string IdentifierInString {
            get {
                return resourceLoader.GetString("IdentifierInString");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property IdentifierInString of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property IdentifierInString of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return resourceLoader.GetString("Title");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Title of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Title of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Description of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Description of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Id of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Id of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property EventCode of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_EventCode_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_EventCode_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property EventCode of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_EventCode_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_EventCode_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EventCode"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of EventCode"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of EventCode"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EventCode of BuildEventCode"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of EventCode of BuildEventCode"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of EventCode of BuildEventCode"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Description"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of BuildEventCode"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Description of BuildEventCode"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description of BuildEventCode"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id of BuildEventCode"".
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of BuildEventCode"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of BuildEventCode"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


    }
}