//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
	using Windows.ApplicationModel.Resources;    
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    public class UIStringResourcePerEntitySolution {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("MSBuildLogsExtended.Resources.WinRT/UIStringResourcePerEntitySolution");
        
        public UIStringResourcePerEntitySolution() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution"".
        /// </summary>
        public static string Solution {
            get {
                return resourceLoader.GetString("Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Loading Solution ..."".
        /// </summary>
        public static string Loading_Solution____ {
            get {
                return resourceLoader.GetString("Loading_Solution____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please select Solution ..."".
        /// </summary>
        public static string Please_select_Solution____ {
            get {
                return resourceLoader.GetString("Please_select_Solution____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rss Title of Solution"".
        /// </summary>
        public static string Rss_Title_of_Solution {
            get {
                return resourceLoader.GetString("Rss_Title_of_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rss Description of Solution"".
        /// </summary>
        public static string Rss_Description_of_Solution {
            get {
                return resourceLoader.GetString("Rss_Description_of_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "AddNew Solution"".
        /// </summary>
        public static string AddNew_Solution {
            get {
                return resourceLoader.GetString("AddNew_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Delete Solution"".
        /// </summary>
        public static string Delete_Solution {
            get {
                return resourceLoader.GetString("Delete_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Details Solution"".
        /// </summary>
        public static string Details_Solution {
            get {
                return resourceLoader.GetString("Details_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Edit Solution"".
        /// </summary>
        public static string Edit_Solution {
            get {
                return resourceLoader.GetString("Edit_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdDescription {
            get {
                return resourceLoader.GetString("IdDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string Id {
            get {
                return resourceLoader.GetString("Id");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return resourceLoader.GetString("IdRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdToolTip {
            get {
                return resourceLoader.GetString("IdToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id has validation error"".
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("IdValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Id validation regular expression"".
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return resourceLoader.GetString("IdValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string Id_is_required {
            get {
                return resourceLoader.GetString("Id_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id"".
        /// </summary>
        public static string ExternalParentIdDescription {
            get {
                return resourceLoader.GetString("ExternalParentIdDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id"".
        /// </summary>
        public static string ExternalParentId {
            get {
                return resourceLoader.GetString("ExternalParentId");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id is required"".
        /// </summary>
        public static string ExternalParentIdRequiredErrorMessage {
            get {
                return resourceLoader.GetString("ExternalParentIdRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id"".
        /// </summary>
        public static string ExternalParentIdToolTip {
            get {
                return resourceLoader.GetString("ExternalParentIdToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id has validation error"".
        /// </summary>
        public static string ExternalParentIdValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("ExternalParentIdValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input External Parent Id validation regular expression"".
        /// </summary>
        public static string ExternalParentIdValueValidationExpression {
            get {
                return resourceLoader.GetString("ExternalParentIdValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string NameDescription {
            get {
                return resourceLoader.GetString("NameDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return resourceLoader.GetString("Name");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string NameRequiredErrorMessage {
            get {
                return resourceLoader.GetString("NameRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string NameToolTip {
            get {
                return resourceLoader.GetString("NameToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name has validation error"".
        /// </summary>
        public static string NameValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("NameValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Name validation regular expression"".
        /// </summary>
        public static string NameValueValidationExpression {
            get {
                return resourceLoader.GetString("NameValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string Name_is_required {
            get {
                return resourceLoader.GetString("Name_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionDescription {
            get {
                return resourceLoader.GetString("DescriptionDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string Description {
            get {
                return resourceLoader.GetString("Description");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description is required"".
        /// </summary>
        public static string DescriptionRequiredErrorMessage {
            get {
                return resourceLoader.GetString("DescriptionRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return resourceLoader.GetString("DescriptionToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description has validation error"".
        /// </summary>
        public static string DescriptionValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("DescriptionValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Description validation regular expression"".
        /// </summary>
        public static string DescriptionValueValidationExpression {
            get {
                return resourceLoader.GetString("DescriptionValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return resourceLoader.GetString("Value");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Value of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Value of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Name of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Name of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Identifier In String"".
        /// </summary>
        public static string IdentifierInString {
            get {
                return resourceLoader.GetString("IdentifierInString");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property IdentifierInString of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property IdentifierInString of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return resourceLoader.GetString("Title");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Title of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Title of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Description of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Description of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Id of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Id of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ExternalParentId"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of ExternalParentId"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of ExternalParentId"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ExternalParentId of Solution"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of ExternalParentId of Solution"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of ExternalParentId of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Name"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Name"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name of Solution"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Name of Solution"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Name of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Description"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Solution"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Description of Solution"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id of Solution"".
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Solution"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


    }
}