//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
	using Windows.ApplicationModel.Resources;    
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    public class UIStringResourcePerEntityBuild {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("MSBuildLogsExtended.Resources.WinRT/UIStringResourcePerEntityBuild");
        
        public UIStringResourcePerEntityBuild() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "Build"".
        /// </summary>
        public static string Build {
            get {
                return resourceLoader.GetString("Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Loading Build ..."".
        /// </summary>
        public static string Loading_Build____ {
            get {
                return resourceLoader.GetString("Loading_Build____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please select Build ..."".
        /// </summary>
        public static string Please_select_Build____ {
            get {
                return resourceLoader.GetString("Please_select_Build____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rss Title of Build"".
        /// </summary>
        public static string Rss_Title_of_Build {
            get {
                return resourceLoader.GetString("Rss_Title_of_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rss Description of Build"".
        /// </summary>
        public static string Rss_Description_of_Build {
            get {
                return resourceLoader.GetString("Rss_Description_of_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "AddNew Build"".
        /// </summary>
        public static string AddNew_Build {
            get {
                return resourceLoader.GetString("AddNew_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Delete Build"".
        /// </summary>
        public static string Delete_Build {
            get {
                return resourceLoader.GetString("Delete_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Details Build"".
        /// </summary>
        public static string Details_Build {
            get {
                return resourceLoader.GetString("Details_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Edit Build"".
        /// </summary>
        public static string Edit_Build {
            get {
                return resourceLoader.GetString("Edit_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdDescription {
            get {
                return resourceLoader.GetString("IdDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string Id {
            get {
                return resourceLoader.GetString("Id");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return resourceLoader.GetString("IdRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdToolTip {
            get {
                return resourceLoader.GetString("IdToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id has validation error"".
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("IdValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Id validation regular expression"".
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return resourceLoader.GetString("IdValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string Id_is_required {
            get {
                return resourceLoader.GetString("Id_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution Id"".
        /// </summary>
        public static string SolutionIdDescription {
            get {
                return resourceLoader.GetString("SolutionIdDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution Id"".
        /// </summary>
        public static string SolutionId {
            get {
                return resourceLoader.GetString("SolutionId");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution Id is required"".
        /// </summary>
        public static string SolutionIdRequiredErrorMessage {
            get {
                return resourceLoader.GetString("SolutionIdRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution Id"".
        /// </summary>
        public static string SolutionIdToolTip {
            get {
                return resourceLoader.GetString("SolutionIdToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution Id has validation error"".
        /// </summary>
        public static string SolutionIdValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("SolutionIdValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Solution Id validation regular expression"".
        /// </summary>
        public static string SolutionIdValueValidationExpression {
            get {
                return resourceLoader.GetString("SolutionIdValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "SolutionId is required"".
        /// </summary>
        public static string SolutionId_is_required {
            get {
                return resourceLoader.GetString("SolutionId_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string NameDescription {
            get {
                return resourceLoader.GetString("NameDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return resourceLoader.GetString("Name");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string NameRequiredErrorMessage {
            get {
                return resourceLoader.GetString("NameRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string NameToolTip {
            get {
                return resourceLoader.GetString("NameToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name has validation error"".
        /// </summary>
        public static string NameValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("NameValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Name validation regular expression"".
        /// </summary>
        public static string NameValueValidationExpression {
            get {
                return resourceLoader.GetString("NameValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string Name_is_required {
            get {
                return resourceLoader.GetString("Name_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionDescription {
            get {
                return resourceLoader.GetString("DescriptionDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string Description {
            get {
                return resourceLoader.GetString("Description");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description is required"".
        /// </summary>
        public static string DescriptionRequiredErrorMessage {
            get {
                return resourceLoader.GetString("DescriptionRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return resourceLoader.GetString("DescriptionToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description has validation error"".
        /// </summary>
        public static string DescriptionValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("DescriptionValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Description validation regular expression"".
        /// </summary>
        public static string DescriptionValueValidationExpression {
            get {
                return resourceLoader.GetString("DescriptionValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Build Start Time"".
        /// </summary>
        public static string BuildStartTimeDescription {
            get {
                return resourceLoader.GetString("BuildStartTimeDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Build Start Time"".
        /// </summary>
        public static string BuildStartTime {
            get {
                return resourceLoader.GetString("BuildStartTime");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Build Start Time is required"".
        /// </summary>
        public static string BuildStartTimeRequiredErrorMessage {
            get {
                return resourceLoader.GetString("BuildStartTimeRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Build Start Time"".
        /// </summary>
        public static string BuildStartTimeToolTip {
            get {
                return resourceLoader.GetString("BuildStartTimeToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Build Start Time has validation error"".
        /// </summary>
        public static string BuildStartTimeValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("BuildStartTimeValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Build Start Time validation regular expression"".
        /// </summary>
        public static string BuildStartTimeValueValidationExpression {
            get {
                return resourceLoader.GetString("BuildStartTimeValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "BuildStartTime is required"".
        /// </summary>
        public static string BuildStartTime_is_required {
            get {
                return resourceLoader.GetString("BuildStartTime_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return resourceLoader.GetString("Value");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Value of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Value of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Name of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Name of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Identifier In String"".
        /// </summary>
        public static string IdentifierInString {
            get {
                return resourceLoader.GetString("IdentifierInString");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property IdentifierInString of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property IdentifierInString of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return resourceLoader.GetString("Title");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Title of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Title of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Description of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Description of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Pub Date"".
        /// </summary>
        public static string PubDate {
            get {
                return resourceLoader.GetString("PubDate");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property PubDate of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property PubDate of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution"".
        /// </summary>
        public static string Solution_S1_1_Name {
            get {
                return resourceLoader.GetString("Solution_S1_1_Name");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Solution_S1_1_Name of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Solution_S1_1_Name of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Id of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Id of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property SolutionId of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property SolutionId of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property BuildStartTime of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property BuildStartTime of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Count Per FK"".
        /// </summary>
        public static string CountPerFK {
            get {
                return resourceLoader.GetString("CountPerFK");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property CountPerFK of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property CountPerFK of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Solution"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Solution"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id of Solution"".
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return resourceLoader.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Solution"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Name"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Name"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name of Build"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Name of Build"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Name of Build"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Description"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Build"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Description of Build"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description of Build"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "BuildStartTime"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of BuildStartTime"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of BuildStartTime"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "From"".
        /// </summary>
        public static string IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of From"".
        /// </summary>
        public static string Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of From"".
        /// </summary>
        public static string Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "From"".
        /// </summary>
        public static string LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of From"".
        /// </summary>
        public static string Description_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of From"".
        /// </summary>
        public static string Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "To"".
        /// </summary>
        public static string IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of To"".
        /// </summary>
        public static string Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of To"".
        /// </summary>
        public static string Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "To"".
        /// </summary>
        public static string UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of To"".
        /// </summary>
        public static string Description_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of To"".
        /// </summary>
        public static string Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Solution"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Solution"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Solution"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id of Solution"".
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return resourceLoader.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Solution"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return resourceLoader.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id of Build"".
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Build"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Build"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


    }
}