//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
	using Windows.ApplicationModel.Resources;    
    
    public class UIStringResourcePerApp {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("MSBuildLogsExtended.Resources.WinRT/UIStringResourcePerApp");
        
        public UIStringResourcePerApp() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "MSBuildLogsExtended"".
        /// </summary>
        public static string Application_Title {
            get {
                return resourceLoader.GetString("Application_Title");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Common_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Common_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string EntityRelated_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of UpdateNameOnly of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string Description_Of_UpdateNameOnly_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("Description_Of_UpdateNameOnly_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "UpdateNameOnly of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string UpdateNameOnly_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("UpdateNameOnly_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of UpdateNameOnly of MSBuildLogsExtended.Build"".
        /// </summary>
        public static string ToolTip_Of_UpdateNameOnly_of_MSBuildLogsExtended_Build {
            get {
                return resourceLoader.GetString("ToolTip_Of_UpdateNameOnly_of_MSBuildLogsExtended_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Common_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Common_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string EntityRelated_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildLogsExtended.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildLogsExtended.BuildLog"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildLogsExtended_BuildLog {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildLogsExtended_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildLogsExtended.BuildLog"".
        /// </summary>
        public static string Common_of_MSBuildLogsExtended_BuildLog {
            get {
                return resourceLoader.GetString("Common_of_MSBuildLogsExtended_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildLogsExtended.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildLogsExtended_BuildLog {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildLogsExtended_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildLogsExtended.BuildLog"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildLogsExtended_BuildLog {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildLogsExtended_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildLogsExtended.BuildLog"".
        /// </summary>
        public static string EntityRelated_of_MSBuildLogsExtended_BuildLog {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildLogsExtended_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildLogsExtended.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_BuildLog {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Common_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Common_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string EntityRelated_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildLogsExtended_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildLogsExtended.Solution"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_Solution {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildLogsExtended_Solution");
            }
        }


    }
}