ALTER TABLE [dbo].[BuildEventCode] CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[Solution] CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[Build] CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[BuildLog] CHECK CONSTRAINT ALL