//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerEntityBuildEventCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerEntityBuildEventCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildLogsExtended.Resources.UIStringResourcePerEntityBuildEventCode", typeof(UIStringResourcePerEntityBuildEventCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNew BuildEventCode.
        /// </summary>
        public static string AddNew_BuildEventCode {
            get {
                return ResourceManager.GetString("AddNew_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildEventCode.
        /// </summary>
        public static string BuildEventCode {
            get {
                return ResourceManager.GetString("BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete BuildEventCode.
        /// </summary>
        public static string Delete_BuildEventCode {
            get {
                return ResourceManager.GetString("Delete_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Description.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCo" +
                        "mmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of EventCode.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfComm" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Id.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIde" +
                        "ntifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Description of BuildEventCode.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescription" +
                        "CommonOftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of EventCode of BuildEventCode.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCo" +
                        "mmonOftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Id of BuildEventCode.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOf" +
                        "ByIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionDescription {
            get {
                return ResourceManager.GetString("DescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string DescriptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return ResourceManager.GetString("DescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description has validation error.
        /// </summary>
        public static string DescriptionValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionValueValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Description validation regular expression.
        /// </summary>
        public static string DescriptionValueValidationExpression {
            get {
                return ResourceManager.GetString("DescriptionValueValidationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details BuildEventCode.
        /// </summary>
        public static string Details_BuildEventCode {
            get {
                return ResourceManager.GetString("Details_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit BuildEventCode.
        /// </summary>
        public static string Edit_BuildEventCode {
            get {
                return ResourceManager.GetString("Edit_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code.
        /// </summary>
        public static string EventCode {
            get {
                return ResourceManager.GetString("EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventCode is required.
        /// </summary>
        public static string EventCode_is_required {
            get {
                return ResourceManager.GetString("EventCode_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code.
        /// </summary>
        public static string EventCodeDescription {
            get {
                return ResourceManager.GetString("EventCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code is required.
        /// </summary>
        public static string EventCodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EventCodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code.
        /// </summary>
        public static string EventCodeToolTip {
            get {
                return ResourceManager.GetString("EventCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Code has validation error.
        /// </summary>
        public static string EventCodeValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("EventCodeValueValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Event Code validation regular expression.
        /// </summary>
        public static string EventCodeValueValidationExpression {
            get {
                return ResourceManager.GetString("EventCodeValueValidationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string Id_is_required {
            get {
                return ResourceManager.GetString("Id_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string IdDescription {
            get {
                return ResourceManager.GetString("IdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier In String.
        /// </summary>
        public static string IdentifierInString {
            get {
                return ResourceManager.GetString("IdentifierInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IdRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string IdToolTip {
            get {
                return ResourceManager.GetString("IdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id has validation error.
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("IdValueValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Id validation regular expression.
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return ResourceManager.GetString("IdValueValidationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventCode.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading BuildEventCode ....
        /// </summary>
        public static string Loading_BuildEventCode____ {
            get {
                return ResourceManager.GetString("Loading_BuildEventCode____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select BuildEventCode ....
        /// </summary>
        public static string Please_select_BuildEventCode____ {
            get {
                return ResourceManager.GetString("Please_select_BuildEventCode____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Error Message of property Description of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build" +
                        "EventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Error Message of property Id of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Error Message of property IdentifierInString of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtende" +
                        "d_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Error Message of property Name of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCo" +
                        "de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Error Message of property Title of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventC" +
                        "ode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Error Message of property Value of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventC" +
                        "ode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss Description of BuildEventCode.
        /// </summary>
        public static string Rss_Description_of_BuildEventCode {
            get {
                return ResourceManager.GetString("Rss_Description_of_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss Title of BuildEventCode.
        /// </summary>
        public static string Rss_Title_of_BuildEventCode {
            get {
                return ResourceManager.GetString("Rss_Title_of_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip of Description.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip of EventCode.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareEventCodeCommonOftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip of Id.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentif" +
                        "ier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip of Description of BuildEventCode.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionComm" +
                        "onOftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip of EventCode of BuildEventCode.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommon" +
                        "OftOfCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip of Id of BuildEventCode.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfById" +
                        "entifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validation Error Message of property Description of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Bui" +
                        "ldEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validation Error Message of property Id of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildEventCo" +
                        "de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validation Error Message of property IdentifierInString of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExten" +
                        "ded_BuildEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validation Error Message of property Name of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildEvent" +
                        "Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validation Error Message of property Title of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildEven" +
                        "tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validation Error Message of property Value of MSBuildLogsExtended.BuildEventCode.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEventCode {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildEven" +
                        "tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of BuildEventCode.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfComm" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventCode of BuildEventCode.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedEventCodeCommonOftOfCommon" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of BuildEventCode.
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }
    }
}
