//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerEntityBuild {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerEntityBuild() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildLogsExtended.Resources.UIStringResourcePerEntityBuild", typeof(UIStringResourcePerEntityBuild).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Loading_Build____ {
            get {
                return ResourceManager.GetString("Loading_Build____", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Please_select_Build____ {
            get {
                return ResourceManager.GetString("Please_select_Build____", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Rss_Title_of_Build {
            get {
                return ResourceManager.GetString("Rss_Title_of_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Rss_Description_of_Build {
            get {
                return ResourceManager.GetString("Rss_Description_of_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AddNew_Build {
            get {
                return ResourceManager.GetString("AddNew_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Delete_Build {
            get {
                return ResourceManager.GetString("Delete_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Details_Build {
            get {
                return ResourceManager.GetString("Details_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Edit_Build {
            get {
                return ResourceManager.GetString("Edit_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdDescription {
            get {
                return ResourceManager.GetString("IdDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IdRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdToolTip {
            get {
                return ResourceManager.GetString("IdToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("IdValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return ResourceManager.GetString("IdValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Id_is_required {
            get {
                return ResourceManager.GetString("Id_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionIdDescription {
            get {
                return ResourceManager.GetString("SolutionIdDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionId {
            get {
                return ResourceManager.GetString("SolutionId", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("SolutionIdRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionIdToolTip {
            get {
                return ResourceManager.GetString("SolutionIdToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionIdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("SolutionIdValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionIdValueValidationExpression {
            get {
                return ResourceManager.GetString("SolutionIdValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SolutionId_is_required {
            get {
                return ResourceManager.GetString("SolutionId_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NameToolTip {
            get {
                return ResourceManager.GetString("NameToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NameValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("NameValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NameValueValidationExpression {
            get {
                return ResourceManager.GetString("NameValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Name_is_required {
            get {
                return ResourceManager.GetString("Name_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DescriptionDescription {
            get {
                return ResourceManager.GetString("DescriptionDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DescriptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return ResourceManager.GetString("DescriptionToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DescriptionValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DescriptionValueValidationExpression {
            get {
                return ResourceManager.GetString("DescriptionValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTimeDescription {
            get {
                return ResourceManager.GetString("BuildStartTimeDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTime {
            get {
                return ResourceManager.GetString("BuildStartTime", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTimeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BuildStartTimeRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTimeToolTip {
            get {
                return ResourceManager.GetString("BuildStartTimeToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTimeValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("BuildStartTimeValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTimeValueValidationExpression {
            get {
                return ResourceManager.GetString("BuildStartTimeValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildStartTime_is_required {
            get {
                return ResourceManager.GetString("BuildStartTime_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdentifierInString {
            get {
                return ResourceManager.GetString("IdentifierInString", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PubDate {
            get {
                return ResourceManager.GetString("PubDate", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Solution_S1_1_Name {
            get {
                return ResourceManager.GetString("Solution_S1_1_Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_SolutionId_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_BuildStartTime_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CountPerFK {
            get {
                return ResourceManager.GetString("CountPerFK", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_Build", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundBuildStartTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


    }
}