//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildLogsExtended.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerEntityBuildLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerEntityBuildLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildLogsExtended.Resources.UIStringResourcePerEntityBuildLog", typeof(UIStringResourcePerEntityBuildLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildLog {
            get {
                return ResourceManager.GetString("BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Loading_BuildLog____ {
            get {
                return ResourceManager.GetString("Loading_BuildLog____", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Please_select_BuildLog____ {
            get {
                return ResourceManager.GetString("Please_select_BuildLog____", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Rss_Title_of_BuildLog {
            get {
                return ResourceManager.GetString("Rss_Title_of_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Rss_Description_of_BuildLog {
            get {
                return ResourceManager.GetString("Rss_Description_of_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AddNew_BuildLog {
            get {
                return ResourceManager.GetString("AddNew_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Delete_BuildLog {
            get {
                return ResourceManager.GetString("Delete_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Details_BuildLog {
            get {
                return ResourceManager.GetString("Details_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Edit_BuildLog {
            get {
                return ResourceManager.GetString("Edit_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdDescription {
            get {
                return ResourceManager.GetString("IdDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IdRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdToolTip {
            get {
                return ResourceManager.GetString("IdToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("IdValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return ResourceManager.GetString("IdValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Id_is_required {
            get {
                return ResourceManager.GetString("Id_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildIdDescription {
            get {
                return ResourceManager.GetString("BuildIdDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildId {
            get {
                return ResourceManager.GetString("BuildId", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BuildIdRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildIdToolTip {
            get {
                return ResourceManager.GetString("BuildIdToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildIdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("BuildIdValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildIdValueValidationExpression {
            get {
                return ResourceManager.GetString("BuildIdValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildId_is_required {
            get {
                return ResourceManager.GetString("BuildId_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeIdDescription {
            get {
                return ResourceManager.GetString("BuildEventCodeIdDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeId {
            get {
                return ResourceManager.GetString("BuildEventCodeId", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BuildEventCodeIdRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeIdToolTip {
            get {
                return ResourceManager.GetString("BuildEventCodeIdToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeIdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("BuildEventCodeIdValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeIdValueValidationExpression {
            get {
                return ResourceManager.GetString("BuildEventCodeIdValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCodeId_is_required {
            get {
                return ResourceManager.GetString("BuildEventCodeId_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageDescription {
            get {
                return ResourceManager.GetString("MessageDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MessageRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageToolTip {
            get {
                return ResourceManager.GetString("MessageToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("MessageValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageValueValidationExpression {
            get {
                return ResourceManager.GetString("MessageValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTimeDescription {
            get {
                return ResourceManager.GetString("EventTimeDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTimeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EventTimeRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTimeToolTip {
            get {
                return ResourceManager.GetString("EventTimeToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTimeValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("EventTimeValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTimeValueValidationExpression {
            get {
                return ResourceManager.GetString("EventTimeValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EventTime_is_required {
            get {
                return ResourceManager.GetString("EventTime_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdentifierInString {
            get {
                return ResourceManager.GetString("IdentifierInString", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PubDate {
            get {
                return ResourceManager.GetString("PubDate", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_PubDate_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Build_B1_1_Name {
            get {
                return ResourceManager.GetString("Build_B1_1_Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Build_B1_1_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Build_B1_1_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Build_B1_1_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Build_B1_1_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Solution_S1_1Id {
            get {
                return ResourceManager.GetString("Solution_S1_1Id", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Solution_S1_1Id_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Solution_S1_1Id_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Solution_S1_1Id_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Solution_S1_1Id_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Solution_S1_1_Name {
            get {
                return ResourceManager.GetString("Solution_S1_1_Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Solution_S1_1_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BuildEventCode_B2_1_Name {
            get {
                return ResourceManager.GetString("BuildEventCode_B2_1_Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_BuildEventCode_B2_1_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_BuildEventCode_B2_1_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_BuildEventCode_B2_1_Name_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_BuildEventCode_B2_1_Name_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_BuildId_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_BuildId_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_BuildId_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_BuildId_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_BuildEventCodeId_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_BuildEventCodeId_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_BuildEventCodeId_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_BuildEventCodeId_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Message_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Message_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Message_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Message_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_EventTime_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_EventTime_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_EventTime_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_EventTime_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CountPerFK {
            get {
                return ResourceManager.GetString("CountPerFK", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_BuildLog {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildLogsExtended_BuildLog", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuild_B1_1OfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuild_B1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuild_B1_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuild_B1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuild_B1_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuild_B1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuild_B1_1OfCommon {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuild_B1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuild_B1_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuild_B1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuild_B1_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuild_B1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfSolution_S1_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuildEventCode_B2_1OfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuildEventCode_B2_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuildEventCode_B2_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuildEventCode_B2_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuildEventCode_B2_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfBuildEventCode_B2_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuildEventCode_B2_1OfCommon {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuildEventCode_B2_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuildEventCode_B2_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuildEventCode_B2_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuildEventCode_B2_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfBuildEventCode_B2_1OfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LowerBound_ID_TextBox_Search_lowerBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("LowerBound_ID_TextBox_Search_lowerBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_LowerBound_ID_TextBox_Search_lowerBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_LowerBound_ID_TextBox_Search_lowerBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpperBound_ID_TextBox_Search_upperBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("UpperBound_ID_TextBox_Search_upperBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_UpperBound_ID_TextBox_Search_upperBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_UpperBound_ID_TextBox_Search_upperBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundEventTimeCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundEventTimeCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuild_B1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfSolution_S1_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdByFKOnlyOfBuildEventCode_B2_1OfByFKOnly", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


    }
}